### ISSUE TITLE
Restore scheduler functionality

### ISSUE THREAD

**Issue by marrrcin** [getindata/kedro-vertexai#4]
Scheduler was temporarily disabled due to slight issues with MLFlow integrations (token obtaining) and not working re-scheduling (old schedules were not disabled).
Restore this functionality in future releases.

**Comment by Lasica** [comment]
Is this still relevant? I don't understand the context of this issue.

**Comment by Stormz4** [comment]
Are the any news about this issue?

**Comment by marrrcin** [comment]
We could potentially use https://cloud.google.com/vertex-ai/docs/pipelines/schedule-pipeline-run#aiplatform_create_pipeline_schedule_sample-python_vertex_ai_sdk 🤔

Let me take it to the team and we'll get back to you :)

**Comment by Stormz4** [comment]
I solved this problem with the following workaround:
1. Compile the Kedro project with kedro vertexai compile
2. Create a PipelineJob object (https://cloud.google.com/python/docs/reference/aiplatform/latest/google.cloud.aiplatform.PipelineJob)
3. Call the function create_schedule of the retrieved PipelineJob (https://cloud.google.com/python/docs/reference/aiplatform/latest/google.cloud.aiplatform.PipelineJob#google_cloud_aiplatform_PipelineJob_create_schedule)

It should be pretty streamlined to implement said solution in Kedro's API.

optional step suggestion (could be a flag inserted through args):
- Check if a job already exists with my desired display name: if it exists, delete it (and recreate it). This is needed since in vertexai you can have multiple pipeline with the same name
